/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fibo_FibLib */
//#include <list>
//#include <stl\_list.h>
//#include <list>
//#include "/Applications/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/list"

// com_example_fibo

#ifndef _Included_com_;example_fibo_FibLib
#define _Included_com_example_fibo_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     _Included_com_example_fibo_FibLib
 * Method:    fibNR
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_fibo_FibLib_fibNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_fibo_mainactivity_FibLib
 * Method:    fibNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_fibo_FibLib_fibNI
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
